baseURL = "http://projectcadi.com/"
languageCode = "en-us"
title = "Project CADI"

theme = "landing-page-hugo"
# https://themes.gohugo.io/landing-page-hugo/

[params]
    description = "Computer Aided Dashboard Instrumentation"

# [[params.social]]
# 	title = "email"
# 	icon = "envelope-o"
# 	url = "mailto:"
# [[params.social]]
# 	title = "twitter"
# 	icon = "twitter"
# 	url = "https://twitter.com/duanenewman"
[[params.social]]
	title = "github"
	icon = "github"
	url = "https://github.com/duanenewman/cadi"
# [[params.social]]
# 	title = "linkedin"
# 	icon = "linkedin"
# 	url = "http://linkedin.com/in/duanenewman"
[[params.social]]
	title = "duane"
	icon = "user"
	url = "http://duanenewman.net"
